[package]
name = "compilation_procedure"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
bson = "2.12.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"